const defaultState = {
    timepieces: 0,
    yarns: 0,
    deathwishes: 0,
    badgePins: 0,
    umbrella: false,
    hookshotBadge: false,
    sprintHat: false,
    brewerHat: false,
    dwellerMask: false,
    iceHat: false,
    timeStopHat: false,
    contractMDS: false,
    contractWell: false,
    contractManor: false,
    contractToilet: false,
    yellowPaintings: false,
    bluePaintings: false,
    greenPaintings: false,
    birdhousePath: false,
    lavaCakePath: false,
    windmillPath: false,
    tbellPath: false,
    yellowMetro: false,
    blueMetro: false,
    greenMetro: false,
    pinkMetro: false,
    baseballBat: false,
    magnetBadge: false,
    noBonkBadge: false,
    scooterBadge: false,
    fastHatterBadge: false,
    projectileBadge: false,
    oneHitHeroBadge: false,
    cameraBadge: false,
    hoverBadge: false,
    compassBadge: false,
    burgerPatty: false,
    burgerCushion: false,
    train: false,
    trainTracks: false,
    crayonBox: false,
    redCrayon: false,
    blueCrayon: false,
    greenCrayon: false,
    ufo: false,
    cow: false,
    sunglassesCow: false,
    tinFoilCow: false,
    necklace: false,
    necklaceBust: false,
    cakeStand: false,
    cake: false,
    cakeSlice: false,
    shortCake: false,
};

function resetState() {
    Object.assign(state, defaultState);
}

const state = { ...defaultState };

module.exports = { state, resetState };